---
language: ruby
jobs:
    - arch: amd64
      rvm: 2.5.8
      env:
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
      - RUBY_GC_HEAP_INIT_SLOTS=600000
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
      - PARALLEL_TEST_PROCESSORS=2
      - TEST_SUITE=vmdb PARALLEL=true
    - arch: amd64
      rvm: 2.6.6
      env:
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
      - RUBY_GC_HEAP_INIT_SLOTS=600000
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
      - PARALLEL_TEST_PROCESSORS=2
      - TEST_SUITE=vmdb PARALLEL=true
    - arch: amd64
      rvm: 2.5.8
      env:
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
      - RUBY_GC_HEAP_INIT_SLOTS=600000
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
      - PARALLEL_TEST_PROCESSORS=2
      - TEST_SUITE=brakeman
    - arch: amd64
      rvm: 2.6.6
      env:
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
      - RUBY_GC_HEAP_INIT_SLOTS=600000
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
      - PARALLEL_TEST_PROCESSORS=2
      - TEST_SUITE=brakeman
    - sudo: required
      group: edge
      virt: lxd
      dist: bionic
      arch: arm64-graviton2
      rvm: 2.5.8
      env:
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
      - RUBY_GC_HEAP_INIT_SLOTS=600000
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
      - PARALLEL_TEST_PROCESSORS=2
      - TEST_SUITE=vmdb PARALLEL=true
    - sudo: required
      group: edge
      virt: lxd
      dist: bionic
      arch: arm64-graviton2
      rvm: 2.5.8
      env:
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
      - RUBY_GC_HEAP_INIT_SLOTS=600000
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
      - PARALLEL_TEST_PROCESSORS=2
      - TEST_SUITE=brakeman
    - sudo: required
      group: edge
      virt: lxd
      dist: bionic
      arch: arm64-graviton2
      rvm: 2.6.6
      env:
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
      - RUBY_GC_HEAP_INIT_SLOTS=600000
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
      - PARALLEL_TEST_PROCESSORS=2
      - TEST_SUITE=vmdb PARALLEL=true
    - sudo: required
      group: edge
      virt: lxd
      dist: bionic
      arch: arm64-graviton2
      rvm: 2.6.6
      env:
      - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
      - RUBY_GC_HEAP_INIT_SLOTS=600000
      - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
      - PARALLEL_TEST_PROCESSORS=2
      - TEST_SUITE=brakeman 

addons:
  postgresql: '10'
before_install:
- sudo sed -i 's/127.0.1.1/127.0.0.1/' /etc/hosts
- git config --global user.name "odidev"
- git config --global user.email "odidev@puresoftware.com"
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
- sudo apt-get install -y libpq-dev libcurl4-openssl-dev
before_script:
- bundle exec rake test:$TEST_SUITE:setup
script:
- bundle exec rake test:$TEST_SUITE
after_failure:
- source ${TRAVIS_BUILD_DIR}/tools/ci/after_failure.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7af45001fe6b7a4039f2
    on_success: change
    on_failure: always
    on_start: never
